services:
  api:
    build:
      context: .
      dockerfile: RealEstateApp.API/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=RealEstateDB;User Id=SA;Password=${SA_PASSWORD};TrustServerCertificate=True;MultipleActiveResultSets=true
      - ConnectionStrings__Redis=redis:6379
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__Issuer=RealEstateApp
      - JwtSettings__Audience=RealEstateApp
      - JwtSettings__ExpiryInMinutes=15
      - CloudinarySettings__CloudName=${CLOUDINARY_CLOUD_NAME}
      - CloudinarySettings__ApiKey=${CLOUDINARY_API_KEY}
      - CloudinarySettings__ApiSecret=${CLOUDINARY_API_SECRET}
      - EmailSettings__SmtpHost=smtp.gmail.com
      - EmailSettings__SmtpPort=587
      - EmailSettings__SenderEmail=${EMAIL_SENDER}
      - EmailSettings__SenderPassword=${EMAIL_PASSWORD}
      - EmailSettings__AppUrl=http://localhost:8080
      - AdminSettings__FirstName=Super
      - AdminSettings__LastName=Admin
      - AdminSettings__Email=${ADMIN_EMAIL}
      - AdminSettings__Password=${ADMIN_PASSWORD}
      - AdminSettings__PhoneNumber=${ADMIN_PHONE}
      - CorsSettings__AllowedOrigins__0=http://localhost:3000
      - CorsSettings__AllowedOrigins__1=http://localhost:5173
    depends_on:
      sqlserver:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - realestate-network
    restart: on-failure


  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P '${SA_PASSWORD}' -Q 'SELECT 1' -No"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - realestate-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - realestate-network

volumes:
  sqlserver-data:
  redis-data:

networks:
  realestate-network:
    driver: bridge